### PR TITLE
Upgrade React native starter

### LINKED ISSUE #1: Upgrade React Native Starter
- [x] Integrate Husky
- [x] Add Github Actions for Linting and Prettier
- [x] Update major dependencies to the Latest version

### PR DESCRIPTION
**Pull request by crstnmac**
Closes #1 

- Replaced tailwind-rn with nativewind
- Added husky with commitlint
- Added github action to lint files

### CODE REVIEW

**Comment by Karthik-B-06** [comment]
LGTM 🎉 
@crstnmac Did you try to run the app in Android Emulator?

**Comment by crstnmac** [comment]
> Oh no will do a check once.

**Comment by crstnmac** [comment]
@Karthik-B-06 Just checked with android 
I am getting a android build error

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-reanimated:mergeDebugNativeLibs'.
> Invalid revision: 3.18.1-g262b901

* Try:
Run with
```


Seems like react-native-reanimated has issue with android build dependency CMAKE. Will be fixed by this week. 

https://github.com/software-mansion/react-native-reanimated/issues/3609

**Comment by Karthik-B-06** [comment]
Sounds good. 👍

**Comment by crstnmac** [comment]
@Karthik-B-06 Fixed android build

**Comment by Karthik-B-06** [comment]
@crstnmac I am hoping the latest Gesture Handler and Reanimated are working well in both iOS and Android.

**Comment by crstnmac** [comment]
@Karthik-B-06 
Added dependency checker 
Fix any React Native package versions that might have compatibility issues.

just run `yarn fix-dependencies`

**Comment by crstnmac** [comment]
> @crstnmac I am hoping the latest Gesture Handler and Reanimated are working well in both iOS and Android.

Libraries will support the latest react native.
Now we can run the deps checker. If any package has a newer version which supports the latest react native version we can upgrade that package using the command `yarn fix-dependencies`

**Comment by Karthik-B-06** [comment]
Great 🎉

**Pull request merged**
